variables:
  PYTHON_VERSION: "3.14.1"
  CUDA_VERSION: "13.0.2"
  CUDNN_VERSION_AMD64: "9.16.0.29"
  CUDNN_VERSION_ARM64: "9.16.0.29"
  CUDNN_CUDA_VERSION_MAJ_MIN_AMD64: "13.0"
  CUDNN_CUDA_VERSION_MAJ_MIN_ARM64: "13.0"
  TAG_VERSION_MAJ_MIN: "false"
  TAG_VERSION_MAJ: "false"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version" && $CUDA_BASE_IMAGE == null && $PYTHON_VERSION =~ /3.12/
      variables:
        BASE_IMAGE_TAG: "12"
    - if: $CI_COMMIT_BRANCH == "freeze-version" && $CUDA_BASE_IMAGE == "ubuntu" && $PYTHON_VERSION =~ /3.12/
      variables:
        BASE_IMAGE: "$CUDA_BASE_IMAGE"
        BASE_IMAGE_TAG: "22.04"
        CUDA_IMAGE_BASE_SUBTAG: "base-$BASE_IMAGE$BASE_IMAGE_TAG"
        CUDA_IMAGE_DEVEL_SUBTAG: "devel-$BASE_IMAGE$BASE_IMAGE_TAG"
        CUDA_IMAGE_SUBTAG: "runtime-$BASE_IMAGE$BASE_IMAGE_TAG"
    - if: $CUDA_BASE_IMAGE == "ubuntu"
      variables:
        BASE_IMAGE: "$CUDA_BASE_IMAGE"
        BASE_IMAGE_TAG: "$CUDA_BASE_IMAGE_TAG"
        CUDA_IMAGE_BASE_SUBTAG: "base-$BASE_IMAGE$BASE_IMAGE_TAG"
        CUDA_IMAGE_DEVEL_SUBTAG: "devel-$BASE_IMAGE$BASE_IMAGE_TAG"
        CUDA_IMAGE_SUBTAG: "runtime-$BASE_IMAGE$BASE_IMAGE_TAG"
    - if: $CI_COMMIT_BRANCH

.before-script-all: &before-script-all
  - |
    if [[ ! -z "$CUDA_IMAGE_SUBTAG" ]]; then
      export CUDA_IMAGE_FLAVOR=`echo $CUDA_IMAGE_SUBTAG | grep -o "base\|runtime\|devel"`
      if [[ "$CUDA_IMAGE_FLAVOR" == "devel" ]]; then
        export CUPTI_AVAILABLE=1
      fi
    fi

.before-script-build: &before-script-build
  - |
    if [[ ! -z "$CI_BUILD_PLATFORMS" ]]; then
      export OS_ARCH=`echo $CI_BUILD_PLATFORMS | tr ' ' '\n' | \
      sed 's|\/||2' | sed 's|\/|-|' | tr '\n' ' '`
    fi
  - |
    export CI_APP_REPO=${CI_APP_REPO:-$CI_REGISTRY_IMAGE}
    if [[ $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "freeze-version" ]]; then
      export CI_APP_TAG=${CI_APP_TAG:-$PYTHON_VERSION}
    else
      export CI_APP_TAG=${CI_APP_TAG:-$CI_COMMIT_SHA}
    fi
  - >
    echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER
    --password-stdin $CI_REGISTRY
  - >
    export VERSION_MAJ_MIN=`echo $PYTHON_VERSION |
    sed -n "s|\([[:digit:]]\+\.[[:digit:]]\+\).*|\1|p"`
    
    export VERSION_MAJ=`echo $PYTHON_VERSION |
    sed -n "s|\([[:digit:]]\+\).*|\1|p"`

.build:
  image: glcr.b-data.ch/docker/docker:dind
  stage: build
  services:
    - name: glcr.b-data.ch/docker/docker:dind
      alias: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    BUILDX_NO_DEFAULT_ATTESTATIONS: "true"
  before_script:
    - *before-script-all
    - *before-script-build
  retry: 2

.post:
  image: glcr.b-data.ch/docker/docker:dind
  stage: .post
  before_script:
    - *before-script-all

build:latest-linux-amd64:
  extends: .build
  tags:
    - arch:amd64
    - os:linux
  script:
    - >
      docker build --pull
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg CUDA_IMAGE
      --build-arg CUDA_VERSION
      --build-arg CUDA_IMAGE_SUBTAG
      --build-arg CUDA_IMAGE_LICENSE
      --build-arg PYTHON_VERSION
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64
      -t $CI_APP_REPO:latest${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64
      -f ver/latest.Dockerfile .
    - |
      if [[ ! -z "$CUDA_IMAGE" && "$CUDA_IMAGE_FLAVOR" != "base" ]]; then
        docker build \
        --build-arg CUDNN_VERSION_AMD64 \
        --build-arg CUDNN_CUDA_VERSION_MAJ_MIN_AMD64 \
        --build-arg LIBNVINFER_VERSION_AMD64 \
        --build-arg LIBNVINFER_CUDA_VERSION_MAJ_MIN_AMD64 \
        --build-arg BUILD_ON_IMAGE=$CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64 \
        --build-arg CUDA_IMAGE_FLAVOR \
        --build-arg CUPTI_AVAILABLE \
        --build-arg BUILD_START=$(date -uIseconds) \
        -t $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64 \
        -t $CI_APP_REPO:latest${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64 \
        -f cuda/latest.Dockerfile .
      fi
    - docker push -a $CI_APP_REPO
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_BUILD_PLATFORMS =~ /(linux\/amd64)/
      changes:
        - ver/latest.Dockerfile
        - cuda/latest.Dockerfile

build:latest-linux-arm64v8:
  extends: .build
  tags:
    - arch:arm64/v8
    - os:linux
  script:
    - >
      docker build --pull
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg CUDA_IMAGE
      --build-arg CUDA_VERSION
      --build-arg CUDA_IMAGE_SUBTAG
      --build-arg CUDA_IMAGE_LICENSE
      --build-arg PYTHON_VERSION
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
      -t $CI_APP_REPO:latest${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
      -f ver/latest.Dockerfile .
    - |
      if [[ ! -z "$CUDA_IMAGE" && "$CUDA_IMAGE_FLAVOR" != "base" ]]; then
        docker build \
        --build-arg CUDNN_VERSION_ARM64 \
        --build-arg CUDNN_CUDA_VERSION_MAJ_MIN_ARM64 \
        --build-arg LIBNVINFER_VERSION_ARM64 \
        --build-arg LIBNVINFER_CUDA_VERSION_MAJ_MIN_ARM64 \
        --build-arg BUILD_ON_IMAGE=$CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8 \
        --build-arg CUDA_IMAGE_FLAVOR \
        --build-arg CUPTI_AVAILABLE \
        --build-arg BUILD_START=$(date -uIseconds) \
        -t $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8 \
        -t $CI_APP_REPO:latest${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8 \
        -f cuda/latest.Dockerfile .
      fi
    - docker push -a $CI_APP_REPO
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_BUILD_PLATFORMS =~ /(linux\/arm64\/v8)/
      changes:
        - ver/latest.Dockerfile
        - cuda/latest.Dockerfile

build:version-linux-amd64:
  extends: .build
  tags:
    - arch:amd64
    - os:linux
  script:
    - >
      docker build --pull
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg CUDA_IMAGE
      --build-arg CUDA_IMAGE_SUBTAG
      --build-arg CUDA_IMAGE_LICENSE
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64
      -f ver/$PYTHON_VERSION.Dockerfile .
    - |
      if [[ ! -z "$CUDA_IMAGE" && "$CUDA_IMAGE_FLAVOR" != "base" ]]; then
        docker build \
        --build-arg BUILD_ON_IMAGE=$CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64 \
        --build-arg CUDA_IMAGE_FLAVOR \
        --build-arg CUPTI_AVAILABLE \
        --build-arg BUILD_START=$(date -uIseconds) \
        -t $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64 \
        -f cuda/$PYTHON_VERSION.Dockerfile .
      fi
    - docker push $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version" && $CI_BUILD_PLATFORMS =~ /(linux\/amd64)/
      changes:
        - ver/$PYTHON_VERSION.Dockerfile

build:version-linux-arm64v8:
  extends: .build
  tags:
    - arch:arm64/v8
    - os:linux
  script:
    - >
      docker build --pull
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg CUDA_IMAGE
      --build-arg CUDA_IMAGE_SUBTAG
      --build-arg CUDA_IMAGE_LICENSE
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
      -f ver/$PYTHON_VERSION.Dockerfile .
    - |
      if [[ ! -z "$CUDA_IMAGE" && "$CUDA_IMAGE_FLAVOR" != "base" ]]; then
        docker build \
        --build-arg BUILD_ON_IMAGE=$CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8 \
        --build-arg CUDA_IMAGE_FLAVOR \
        --build-arg CUPTI_AVAILABLE \
        --build-arg BUILD_START=$(date -uIseconds) \
        -t $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8 \
        -f cuda/$PYTHON_VERSION.Dockerfile .
      fi
    - docker push $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version" && $CI_BUILD_PLATFORMS =~ /(linux\/arm64\/v8)/
      changes:
        - ver/$PYTHON_VERSION.Dockerfile

build-manifest:latest-linux-multiarch:
  extends: .build
  needs: ["build:latest-linux-amd64", "build:latest-linux-arm64v8"]
  script:
    - |
      for i in $OS_ARCH; do
        export CI_MANIFEST_LIST="$CI_MANIFEST_LIST $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-$i"
      done
    - |
      docker manifest create $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR $CI_MANIFEST_LIST
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR \
          $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR
      
      docker manifest create $CI_APP_REPO:latest${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR $CI_MANIFEST_LIST
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:latest${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR \
          $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:latest${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR
      
      docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR $CI_MANIFEST_LIST
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ_MIN${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR \
          $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR
      
      docker manifest create $CI_APP_REPO:$VERSION_MAJ${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR $CI_MANIFEST_LIST
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR \
          $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$VERSION_MAJ${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR
    - |
      if [[ "$CUDA_IMAGE_FLAVOR" == "runtime" ]]; then
        docker manifest create $CI_APP_REPO:$CI_APP_TAG $CI_MANIFEST_LIST
        if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
          docker manifest annotate --variant v8 $CI_APP_REPO:$CI_APP_TAG \
            $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
        fi
        docker manifest push $CI_APP_REPO:$CI_APP_TAG
        
        docker manifest create $CI_APP_REPO:latest $CI_MANIFEST_LIST
        if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
          docker manifest annotate --variant v8 $CI_APP_REPO:latest \
            $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
        fi
        docker manifest push $CI_APP_REPO:latest
        
        docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN $CI_MANIFEST_LIST
        if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
          docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ_MIN \
            $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
        fi
        docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN
        
        docker manifest create $CI_APP_REPO:$VERSION_MAJ $CI_MANIFEST_LIST
        if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
          docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ \
            $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
        fi
        docker manifest push $CI_APP_REPO:$VERSION_MAJ
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - ver/latest.Dockerfile
        - cuda/latest.Dockerfile

build-manifest:version-linux-multiarch:
  extends: .build
  needs: ["build:version-linux-amd64", "build:version-linux-arm64v8"]
  script:
    - |
      for i in $OS_ARCH; do
        export CI_MANIFEST_LIST="$CI_MANIFEST_LIST $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-$i"
      done
    - |
      docker manifest create $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR $CI_MANIFEST_LIST
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR \
          $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR
      
      if [[ "$TAG_VERSION_MAJ_MIN" == "true" ]]; then
        docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR $CI_MANIFEST_LIST
        if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
          docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ_MIN${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR \
            $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
        fi
        docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR
      fi
      
      if [[ "$TAG_VERSION_MAJ" == "true" ]]; then
        docker manifest create $CI_APP_REPO:$VERSION_MAJ${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR $CI_MANIFEST_LIST
        if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
          docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR \
            $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
        fi
        docker manifest push $CI_APP_REPO:$VERSION_MAJ${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR
      fi
    - |
      if [[ "$CUDA_IMAGE_FLAVOR" == "runtime" ]]; then
        docker manifest create $CI_APP_REPO:$CI_APP_TAG $CI_MANIFEST_LIST
        if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
          docker manifest annotate --variant v8 $CI_APP_REPO:$CI_APP_TAG \
            $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
        fi
        docker manifest push $CI_APP_REPO:$CI_APP_TAG
        
        if [[ "$TAG_VERSION_MAJ_MIN" == "true" ]]; then
          docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN $CI_MANIFEST_LIST
          if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
            docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ_MIN \
              $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
          fi
          docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN
        fi
        
        if [[ "$TAG_VERSION_MAJ" == "true" ]]; then
          docker manifest create $CI_APP_REPO:$VERSION_MAJ $CI_MANIFEST_LIST
          if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
            docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ \
              $CI_APP_REPO:$CI_APP_TAG${CUDA_IMAGE_FLAVOR:+-}$CUDA_IMAGE_FLAVOR-linux-arm64v8
          fi
          docker manifest push $CI_APP_REPO:$VERSION_MAJ
        fi
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version"
      changes:
        - ver/$PYTHON_VERSION.Dockerfile

trigger-latest-build:
  extends: .post
  stage: .post
  needs: ["build-manifest:latest-linux-multiarch"]
  before_script:
    - apk upgrade --no-cache
    - apk add --update --no-cache curl
  script:
    - curl -X POST -F token=$PYTHON_BASE -F ref=main https://gitlab.b-data.ch/api/v4/projects/288/trigger/pipeline
  rules:
    - if: $CUDA_IMAGE
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - ver/latest.Dockerfile
        - cuda/latest.Dockerfile

trigger-version-build:
  extends: .post
  stage: .post
  needs: ["build-manifest:version-linux-multiarch"]
  before_script:
    - apk upgrade --no-cache
    - apk add --update --no-cache curl
  script:
    - curl -X POST -F token=$PYTHON_BASE -F ref=freeze-version https://gitlab.b-data.ch/api/v4/projects/288/trigger/pipeline
  rules:
    - if: $CUDA_IMAGE
      when: never
    - if: $CI_COMMIT_BRANCH == "freeze-version"
      changes:
        - ver/$PYTHON_VERSION.Dockerfile

trigger-latest-cuda-build:
  extends: .post
  stage: .post
  needs: ["build-manifest:latest-linux-multiarch"]
  before_script:
    - apk upgrade --no-cache
    - apk add --update --no-cache curl
  script:
    - curl -X POST -F token=$CUDA_PYTHON_BASE -F ref=main https://gitlab.b-data.ch/api/v4/projects/319/trigger/pipeline
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CUDA_IMAGE_SUBTAG =~ /runtime/
      changes:
        - ver/latest.Dockerfile
        - cuda/latest.Dockerfile

trigger-version-cuda-build:
  extends: .post
  stage: .post
  needs: ["build-manifest:version-linux-multiarch"]
  before_script:
    - apk upgrade --no-cache
    - apk add --update --no-cache curl
  script:
    - curl -X POST -F token=$CUDA_PYTHON_BASE -F ref=freeze-version https://gitlab.b-data.ch/api/v4/projects/319/trigger/pipeline
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version" && $CUDA_IMAGE_SUBTAG =~ /runtime/
      changes:
        - ver/$PYTHON_VERSION.Dockerfile

trigger-latest-cuda-self-build:
  extends: .post
  stage: .post
  needs: ["build-manifest:latest-linux-multiarch"]
  before_script:
    - apk upgrade --no-cache
    - apk add --update --no-cache curl
  script:
    - curl -X POST -F token=$CUDA_PYTHON_VER -F ref=main -F "variables[CUDA_IMAGE_SUBTAG]=$CUDA_IMAGE_BASE_SUBTAG" https://gitlab.b-data.ch/api/v4/projects/318/trigger/pipeline
    - curl -X POST -F token=$CUDA_PYTHON_VER -F ref=main -F "variables[CUDA_IMAGE_SUBTAG]=$CUDA_IMAGE_DEVEL_SUBTAG" https://gitlab.b-data.ch/api/v4/projects/318/trigger/pipeline
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CUDA_IMAGE_SUBTAG =~ /runtime/
      changes:
        - ver/latest.Dockerfile
        - cuda/latest.Dockerfile

trigger-version-cuda-self-build:
  extends: .post
  stage: .post
  needs: ["build-manifest:version-linux-multiarch"]
  before_script:
    - apk upgrade --no-cache
    - apk add --update --no-cache curl
  script:
    - curl -X POST -F token=$CUDA_PYTHON_VER -F ref=freeze-version -F "variables[CUDA_IMAGE_SUBTAG]=$CUDA_IMAGE_BASE_SUBTAG" https://gitlab.b-data.ch/api/v4/projects/318/trigger/pipeline
    - curl -X POST -F token=$CUDA_PYTHON_VER -F ref=freeze-version -F "variables[CUDA_IMAGE_SUBTAG]=$CUDA_IMAGE_DEVEL_SUBTAG" https://gitlab.b-data.ch/api/v4/projects/318/trigger/pipeline
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version" && $CUDA_IMAGE_SUBTAG =~ /runtime/
      changes:
        - ver/$PYTHON_VERSION.Dockerfile
